spring:
  datasource:
    url: jdbc:mysql://localhost:3306/campus_hitchhike?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8081